name: Matrix Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main
jobs:
  matrix_test:
    strategy:
      matrix:
        version: [18, 20, 22, 24]
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Lint
        run: pnpm lint
      - name: Types
        run: pnpm tsc
